services:
  # FastAPI OCR Service
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aip-ocr-api
    ports:
      - "8500:8000"
    environment:
      - LOG_LEVEL=INFO
      - ENABLE_FILE_LOGGING=false
      - DOTS_OCR_URL=http://dots-ocr:8000
    volumes:
      - uploads:/tmp/uploads
    depends_on:
      - dots-ocr
    networks:
      - ocr-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Dots OCR Service
  dots-ocr:
    build:
      context: .
      dockerfile: Dockerfile.dots-ocr-cpu
    container_name: dots-ocr-service
    ports:
      - "8501:8000"  # Map to different port to avoid conflicts
    volumes:
      # Mount model directory (you need to download the model first)
      # Model URL: https://www.modelscope.cn/models/rednote-hilab/dots.ocr
      - ./models/dots.ocr:/workspace/weights/DotsOCR:ro
    environment:
      - VLLM_CPU_KVCACHE_SPACE=4
      - VLLM_CPU_OMP_THREADS_BIND=auto
      - VLLM_LOGGING_LEVEL=INFO
      - PYTHONPATH=/workspace/weights:/workspace
      - TORCH_DEVICE=cpu
      - CUDA_VISIBLE_DEVICES=""
      - VLLM_DEVICE=cpu
      - VLLM_PLATFORM=cpu
    networks:
      - ocr-network
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
    shm_size: 4g
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # OCR service might take longer to start

  # Optional: Redis for caching (if needed)
  redis:
    image: redis:7-alpine
    container_name: ocr-redis
    ports:
      - "6380:6379"  # Changed to avoid conflict with existing Redis on 6379
    volumes:
      - redis_data:/data
    networks:
      - ocr-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Optional: PostgreSQL for storing OCR results/metadata
  postgres:
    image: postgres:15-alpine
    container_name: ocr-postgres
    ports:
      - "5433:5432"  # Changed to avoid conflict with existing PostgreSQL on 5432
    environment:
      - POSTGRES_DB=ocr_db
      - POSTGRES_USER=ocr_user
      - POSTGRES_PASSWORD=ocr_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ocr-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ocr_user -d ocr_db"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  uploads:
    driver: local
  models:
    driver: local
  ocr_cache:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  ocr-network:
    driver: bridge
