services:
  # FastAPI OCR Service
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aip-ocr-api
    ports:
      - "8500:8000"
    environment:
      - LOG_LEVEL=INFO
      - ENABLE_FILE_LOGGING=false
      # Allow overriding dots.ocr URL via env; default to localhost:8501
      - DOTS_OCR_URL=${DOTS_OCR_URL:-http://localhost:8501}
    volumes:
      - uploads:/tmp/uploads
    networks:
      - ocr-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Redis for caching (if needed)
  redis:
    image: redis:7-alpine
    container_name: ocr-redis
    ports:
      - "6380:6379"  # Changed to avoid conflict with existing Redis on 6379
    volumes:
      - redis_data:/data
    networks:
      - ocr-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Optional: PostgreSQL for storing OCR results/metadata
  postgres:
    image: postgres:15-alpine
    container_name: ocr-postgres
    ports:
      - "5433:5432"  # Changed to avoid conflict with existing PostgreSQL on 5432
    environment:
      - POSTGRES_DB=ocr_db
      - POSTGRES_USER=ocr_user
      - POSTGRES_PASSWORD=ocr_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ocr-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ocr_user -d ocr_db"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  uploads:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  ocr-network:
    driver: bridge
